#############################################
# Generic Bacterial Infection Model (FINAL)
# - Cardinal temperature response
# - Multiplication–Dispersal–Infection structure
# - Different dispersal pathways per disease
#############################################

# -------------------------------
# 1. INPUT DATA (example)
# -------------------------------

data <- data.frame(
  date = seq(as.Date("2024-04-01"), as.Date("2024-04-30"), by = "day"),
  temp = runif(30, 5, 35),      # daily mean temperature
  rh   = runif(30, 50, 100),    # relative humidity
  rain = runif(30, 0, 20),      # rainfall amount
  wind = runif(30, 0, 10),      # wind speed
  vulnerable_period = ifelse(1:30 %in% 10:20, 1, 0)
  # vulnerable_period:
  # 1 = host tissue / growth stage is vulnerable
  # 0 = host is not in a vulnerable stage
  # This replaces bloom so the same base model can be used across diseases.
)

# -------------------------------
# 2. GLOBAL PARAMETERS
# -------------------------------

global_params <- list(
  risk_threshold = 0.5,     # Empirical management threshold, thus requires 
                            # calibration with observed disease incidence
  risk_window = 3,          # moving average window for decision support
  growth_period = 3         # Number of preceding days used to calculate N
)

# -------------------------------
# 3. DISEASE-SPECIFIC PARAMETERS
# -------------------------------

disease_params <- list(
  
  fire_blight = list(  ##화상병
    N0 = 0.15,             # Initial inoculum pressure (0-1)
                           # Starting bacterial population level at day 1

    mu_max = 0.30,         # Maximum bacterial growth rate
                           # Growth rate under optimal temperature and RH
    
    T_min = 4,             # Minimum temperature for growth (°C)
                           # Growth ceases below this temperature
    
    T_opt = 28,            # Optimum temperature for growth (°C)
                           # Maximum growth occurs near this temperature
    
    T_max = 36,            # Maximum temperature for growth (°C)
                           # Growth ceases above this temperature
    
    wet_thresh = 60,       # Relative humidity threshold (%)
                           # Wetness response reaches 0.5 at this RH
    
    rain_thresh = 0.25,    # Rainfall threshold (mm)
                           # Wetness response = 1 when daily rain >= this value
    
    rain_coeff = 0.055,    # Rain-driven dispersal coefficient
                           # Contribution of rainfall to bacterial movement
    
    wind_coeff = 0.030,    # Wind-driven dispersal coefficient
                           # Contribution of wind to bacterial movement
    
    interaction_coeff = 0.0030,    # Rain × wind interaction coefficient
    # Additional dispersal generated by combined rainfall and wind events
    
    insect_coeff = 0.10,   # Insect-mediated dispersal probability
    # Additional dispersal pathway independent of weather
    
    use_rain = TRUE,       # Include rain dispersal pathway
    use_wind = TRUE,       # Include wind dispersal pathway
    use_interaction = TRUE,# Include rain × wind interaction pathway
    use_insect = TRUE,     # Include insect-mediated dispersal
    use_dispersal = TRUE,  # Calculate dispersal module D
    
    use_vulnerable_period = TRUE,
    # Host susceptibility period required
    # (flowering, young tissue, wound period, etc.)
    
    risk_threshold = 0.45  # Spray decision threshold
    # 3-day average risk above this value
    # triggers management action
  ),
  
  bacterial_spot = list(  ##고추세균성점무늬병
    N0 = 0.08,
    
    # Xanthomonas arboricola pv. pruni:
    # infection tested from 5–35 C;
    # infection optimum estimated at 28.9 C;
    # in vitro growth reported from 5–34 C, not above 35 C.
    mu_max = 0.26,
    T_min = 5,
    T_opt = 29,
    T_max = 35,
    
    # Leaf wetness is required; warm, wet, rainy/dewy conditions are key.
    wet_thresh = 82,
    rain_thresh = 0.25,
    
    # Mainly rain splash / wetness-driven.
    rain_coeff = 0.070,
    wind_coeff = 0.005,
    interaction_coeff = 0.0005,
    insect_coeff = 0.00,
    
    use_rain = TRUE,
    use_wind = FALSE,
    use_interaction = FALSE,
    use_insect = FALSE,
    use_dispersal = TRUE,
    use_vulnerable_period = TRUE,
    
    # PLOS model used S' = 0.5 as infection-risk threshold;
    # in this multiplied N*D*I model, slightly lower is reasonable.
    risk_threshold = 0.40
  ),
  
  bacterial_blight = list( ##벼 흰잎마름병
    N0 = 0.12,
    
    # Rice bacterial blight / Xanthomonas oryzae pv. oryzae:
    # disease-favoring environment commonly reported as 25–34 C
    # and RH > 70%.
    mu_max = 0.27,
    T_min = 10,
    T_opt = 30,
    T_max = 38,
    
    wet_thresh = 70,
    rain_thresh = 0.25,
    
    # Strong winds and continuous heavy rain favor spread.
    rain_coeff = 0.060,
    wind_coeff = 0.030,
    interaction_coeff = 0.0030,
    insect_coeff = 0.00,
    
    use_rain = TRUE,
    use_wind = TRUE,
    use_interaction = TRUE,
    use_insect = FALSE,
    use_dispersal = TRUE,
    use_vulnerable_period = TRUE,
    
    risk_threshold = 0.42
  ),
  
  ralstonia = list(  ##고추풋마름병
    N0 = 0.30,
    
    # Ralstonia solanacearum:
    # warm-climate soilborne pathogen;
    # in vitro maximum growth often around 30 C,
    # bacterial wilt intensity can be high at 30–35 C depending on host/root injury.
    mu_max = 0.32,
    T_min = 10,
    T_opt = 30,
    T_max = 40,
    
    # RH is only a weak proxy here; later soil moisture/root infection module needed.
    wet_thresh = 75,
    rain_thresh = 0.25,
    
    # Base module keeps aboveground dispersal off.
    rain_coeff = 0.000,
    wind_coeff = 0.000,
    interaction_coeff = 0.000,
    insect_coeff = 0.00,
    
    use_rain = FALSE,
    use_wind = FALSE,
    use_interaction = FALSE,
    use_insect = FALSE,
    use_dispersal = FALSE,
    use_vulnerable_period = FALSE,
    
    risk_threshold = 0.50
  )
)

# -------------------------------
# 4. PARAMETER VALIDATION
# -------------------------------

validate_disease_params <- function(p){
  
  if(!(p$T_min < p$T_opt && p$T_opt < p$T_max)){
    stop("Temperature parameters must satisfy T_min < T_opt < T_max.")
  }
  
  if(p$N0 < 0 || p$N0 > 1){
    stop("N0 must be between 0 and 1.")
  }

  if(p$mu_max < 0){
    stop("mu_max must be non-negative.")
  }

  if(p$rain_thresh < 0){
    stop("rain_thresh must be non-negative.")
  }
  
  if(p$rain_coeff < 0 || p$wind_coeff < 0 || 
     p$interaction_coeff < 0 || p$insect_coeff < 0){
    stop("Dispersal coefficients must be non-negative.")
  }
}

# -------------------------------
# 5. CARDINAL TEMPERATURE FUNCTION
# -------------------------------

temp_response <- function(T, T_min, T_opt, T_max){
  
  if(!(T_min < T_opt && T_opt < T_max)){
    stop("Temperature parameters must satisfy T_min < T_opt < T_max.")
  }
  
  response <- rep(0, length(T))
  
  valid <- T > T_min & T < T_max
  
  exponent <- (T_max - T_opt) / (T_opt - T_min)
  
  response[valid] <-
    ((T[valid] - T_min) *
       (T_max - T[valid])^exponent) /
    ((T_opt - T_min) *
       (T_max - T_opt)^exponent)
  
  response <- pmax(0, pmin(response, 1))
  
  return(response)
}

# -------------------------------
# 5-1. HUMIDITY RESPONSE FUNCTION
# -------------------------------

# f_RH(RH) = 1 / (1 + exp[-k_w * (RH - RH_th)])
# RH_th: RH threshold where the response reaches 0.5 (wet_thresh)
# k_w  : logistic slope (fixed at 0.3)

rh_response <- function(RH, RH_th, k_w = 0.3){
  plogis(k_w * (RH - RH_th))
}

# -------------------------------
# 5-2. WETNESS RESPONSE FUNCTION
# -------------------------------

# W(RH, Rain) = 1                                  if Rain >= Rain_th
#             = 1 / (1 + exp[-k * (RH - RH_th)])   if Rain <  Rain_th

wetness_response <- function(RH, Rain, RH_th, Rain_th, k = 0.3){
  ifelse(Rain >= Rain_th, 1, rh_response(RH, RH_th, k))
}

# -------------------------------
# 6. MULTIPLICATION
# -------------------------------

calc_population <- function(data, disease_param, growth_period){
  validate_disease_params(disease_param)

  if(length(growth_period) != 1 || is.na(growth_period) ||
     growth_period < 0 || growth_period != as.integer(growth_period)){
    stop("growth_period must be a non-negative integer.")
  }

  n <- nrow(data)
  if(n == 0){
    return(numeric(0))
  }

  # Daily growth rate r_t = mu_max * f_T(T) * f_RH(RH).
  temp_eff <- temp_response(
    data$temp,
    disease_param$T_min,
    disease_param$T_opt,
    disease_param$T_max
  )
  rh_eff <- rh_response(data$rh, disease_param$wet_thresh)
  r <- disease_param$mu_max * temp_eff * rh_eff

  N <- numeric(n)

  # For each date, restart from N0 and apply available daily growth rates
  # from t - growth_period through t (growth_period + 1 rates when a full history is available).
  for(t in seq_len(n)){
    first_day <- max(1, t - growth_period)
    current_N <- disease_param$N0

    for(s in first_day:t){
      current_N <- current_N + r[s] * current_N * (1 - current_N)
      current_N <- max(0, min(current_N, 1))
    }

    N[t] <- current_N
  }

  return(N)
}
# -------------------------------
# 7. DISPERSAL
# -------------------------------

calc_dispersal <- function(data, disease_param){
  
  total_effect <- rep(0, nrow(data))
  
  if(disease_param$use_rain){
    total_effect <- total_effect +
      disease_param$rain_coeff * data$rain
  }
  
  if(disease_param$use_wind){
    total_effect <- total_effect +
      disease_param$wind_coeff * data$wind
  }
  
  if(disease_param$use_interaction){
    total_effect <- total_effect +
      disease_param$interaction_coeff * data$rain * data$wind
  }
  
  D_weather <- 1 - exp(-total_effect)
  
  if(disease_param$use_insect){
    
    D_insect <- rep(disease_param$insect_coeff, nrow(data))
    
    D <- 1 - (1 - D_weather) * (1 - D_insect)
    
  } else {
    D <- D_weather
  }
  
  D <- pmax(0, pmin(D, 1))
  
  return(D)
}

# -------------------------------
# 8. INFECTION
# -------------------------------

calc_infection <- function(data, disease_param){
  
  wetness <- wetness_response(
    data$rh,
    data$rain,
    disease_param$wet_thresh,
    disease_param$rain_thresh
  )
  
  temp_eff <- temp_response(
    data$temp,
    disease_param$T_min,
    disease_param$T_opt,
    disease_param$T_max
  )
  
  if(disease_param$use_vulnerable_period){
    vp_factor <- data$vulnerable_period
  } else {
    vp_factor <- rep(1, nrow(data))
  }
  
  I <- wetness * temp_eff * vp_factor
  
  I <- pmax(0, pmin(I, 1))
  
  return(I)
}

# -------------------------------
# 9. RUN MODEL
# -------------------------------

run_model <- function(data, disease_param, growth_period = 3){
  
  validate_disease_params(disease_param)
  
  N <- calc_population(data, disease_param, growth_period)
  
  I <- calc_infection(data, disease_param)
  
  if(disease_param$use_dispersal){
    
    D <- calc_dispersal(data, disease_param)
    
    Risk <- N * D * I
    
  } else {
    
    D <- rep(1, nrow(data))
    
    Risk <- N * I
  }
  
  Risk <- pmax(0, pmin(Risk, 1))
  
  result <- data.frame(
    date = data$date,
    N = N,
    D = D,
    I = I,
    Risk = Risk
  )
  
  return(result)
}

# -------------------------------
# 10. SPRAY DECISION
# -------------------------------

spray_decision <- function(result, disease_param, global_params){
  
  risk_window <- global_params$risk_window
  
  risk_3day_avg <- stats::filter(
    result$Risk,
    rep(1 / risk_window, risk_window),
    sides = 1
  )
  
  risk_3day_avg <- as.numeric(risk_3day_avg)
  
  risk_3day_avg[is.na(risk_3day_avg)] <- 0
  
  threshold <- disease_param$risk_threshold
  
  spray <- ifelse(risk_3day_avg > threshold, 1, 0)
  
  result$risk_3day_avg <- risk_3day_avg
  result$spray <- spray
  
  return(result)
}

# -------------------------------
# 11. RUN
# -------------------------------

disease <- "fire_blight"

disease_param <- disease_params[[disease]]

res <- run_model(data, disease_param, global_params$growth_period)

res <- spray_decision(res, disease_param, global_params)

print(res)

# -------------------------------
# 12. VISUALIZATION
# -------------------------------

plot(
  res$date,
  res$Risk,
  type = "l",
  col = "red",
  main = paste("Risk -", disease),
  ylab = "Risk",
  xlab = "Date"
)

lines(res$date, res$risk_3day_avg, col = "blue")

legend(
  "topright",
  legend = c("Daily Risk", "3-day Average Risk"),
  col = c("red", "blue"),
  lty = 1
)